const allCommodities = [
    "AcryliPlex Composite",
    "Agricium",
    "Agricium (Raw)",
    "Agricultural Supplies",
    "Aluminum",
    "Aluminum (Raw)",
    "Amioshi Plague",
    "Aphorite",
    "Argon",
    "Astatine",
    "Atlasium",
    "Beryl",
    "Beryl (Raw)",
    "Bexalite",
    "Bexalite (Raw)",
    "Bioplastic",
    "Borase",
    "Borase (Raw)",
    "Cadmium Allinide",
    "Carbon-Silk",
    "Chlorine",
    "Compboard",
    "Copper",
    "Copper (Raw)",
    "Corundum",
    "Corundum (Raw)",
    "Decari Pod",
    "Degnous Root",
    "Diamond",
    "Diamond (Raw)",
    "Diamond Laminate",
    "Diluthermex",
    "Distilled Spirits",
    "Dolivine",
    "Dymantium",
    "DynaFlex",
    "Elespo",
    "Fluorine",
    "Gold",
    "Gold (Raw)",
    "Golden Medmon",
    "Hadanite",
    "Helium",
    "Hephaestanite",
    "Hephaestanite (Raw)",
    "Hydrogen",
    "Inert Materials",
    "Iodine",
    "Jahlium",
    "Janalite",
    "Jumping Limes",
    "Laranite",
    "Laranite (Raw)",
    "Lastaphrene",
    "Luminalia Gift",
    "Lunes",
    "Lycara",
    "Magnesium",
    "Medical Supplies",
    "Neograph",
    "Omnapoxy",
    "Partillium",
    "Pitambu",
    "Processed Food",
    "Prota",
    "Quantanium",
    "Quantanium (Raw)",
    "Quartz",
    "Quartz (Raw)",
    "Ranta Dung",
    "Recycled Material Composite",
    "Revenant Pod",
    "Revenant Tree Pollen",
    "Sarilus",
    "Scrap",
    "Silnex",
    "Stims",
    "Stone Bug Shell",
    "Sunset Berries",
    "Taranite",
    "Taranite (Raw)",
    "Thermalfoam",
    "Titanium",
    "Titanium (Raw)",
    "Tungsten",
    "Tungsten (Raw)",
    "Waste",
    "Xa'Pyen",
    "Year Of The Dog Envelope",
    "Year Of The Monkey Envelope",
    "Year Of The Pig Envelope",
    "Year Of The Rooster Envelope",
    "Zeta-Prolanide",
];

export default allCommodities;
