export const PyroSystemData = {
    planets: ['Pyro 1', 'Monox', 'Bloom', 'Pyro IV', 'Pyro V', 'Terminus'],
    moons: ['Ignis', 'Vatra', 'Adir', 'Fairo', 'Fuego', 'Vuur'],
    stations: ['Ruin Station', 'Orbituary', 'Patch City', 'Starlight Service Station', 'Checkmate', 'Rods Fuel N Supplies', 'Endgame', 'Dudley & Daughters', 'Rats Net', 'Megumi Refueling', 'Gaslight'],
    outposts: ['Stags Rut', 'Arid Reach', 'Jacksons Swap', 'Narenas Rest', 'The Golden Riviera', 'Frigid Knot', 'ShadowFall', 'Fallow Field', 'Goners Deal', 'Sacrens Plot', 'Rough Landing', 'Blackrock Exchange', 'Canard View', 'Stonetree'],
    miningoutpost: ['Yangs Place', 'Ostlers Claim', 'Last Ditch', 'Cravers Ridge', 'Bueno Ravine'],
    farmingoutpost: ['The Yard', 'Shepherds Rest', 'Scrapers Turn', 'Bullocks Reach', 'Kinder Plots'],
    salvageyards: ['Rsutville', 'Sunset Mesa', 'Windfall', 'Chawlas Breach', 'Last Landings'],

    Dropoffpoints: {
        'Pyro 1': ['--Outposts--', 'Stags Rut', '--Salvage Yards--', 'Rsutville'],
        Monox: ['--Outposts--', 'Arid Reach', 'Jacksons Swap', '--Mining Outposts--', 'Yangs Place', 'Ostlers Claim', 'Last Ditch', '--Salvage Yards--', 'Sunset Mesa'],
        Bloom: ['--Outposts--', 'Narenas Rest', 'The Golden Riviera', 'Frigid Knot', 'ShadowFall', '--Salvage Yards--', 'Windfall', '--Farming Outposts--', 'The Yard', 'Shepherds Rest', '--Mining Outposts--', 'Cravers Ridge', 'Bueno Ravine'],
        'Pyro IV': ['--Outposts--', 'Fallow Field', 'Goners Deal', 'Sacrens Plot', '--Salvage Yards--', 'Chawlas Breach'],
        Terminus: ['--Outposts--', 'Rough Landing', 'Blackrock Exchange', 'Canard View', 'Stonetree', '--Farming Outposts--', 'Scrapers Turn', 'Bullocks Reach', 'Kinder Plots', '--Salvage Yards--', 'Last Landings'],
        'Pyro V': {
            Ignis: ['--Outposts--', 'Ashland', 'Kabirs Post'],
            Vatra: ['--Salvage Yards--', 'Seers Canyon'],
            Adir: ['--Outposts--', 'Prophets Peak'],
        }
    },

    OCRCORRECTIONS: {
        'Ruin Station': ['Rum Station', 'Run Station'],
        'Orbituary': ['Orbituary', 'Orbitury'],
        'Patch City': ['Parch City', 'Path City'],
        'Starlight Service Station': ['Starlight Servce Station', 'Starlght Service Station'],
        'Rods Fuel N Supplies': ['Rod Fuel N Supplies', 'Rods Fuel & Supplies'],
        'Stags Rut': ['Stags Rut', 'Stags Rut'],
        'Arid Reach': ['Arid Reach', 'Arid Beach'],
        'Jacksons Swap': ['Jackson Swap', 'Jacksons Swamp'],
        'Narenas Rest': ['Narenas Rest', 'Narenas Nest'],
        'The Golden Riviera': ['The Golden Riveria', 'Golden Riviera'],
        'Frigid Knot': ['Frigid Not', 'Frigid Knob'],
        'ShadowFall': ['Shadowfall', 'Shadow Fall'],
        'Fallow Field': ['Fallow Field', 'Follow Field'],
        'Goners Deal': ['Goners Deal', 'Goners Meal'],
        'Sacrens Plot': ['Sacrens Plot', 'Sacrens Pot'],
        'Rough Landing': ['Rough Landing', 'Rough Landng'],
        'Blackrock Exchange': ['Blackrock Exchange', 'Black Rock Exchange'],
        'Canard View': ['Canard View', 'Canard Vue'],
        'Stonetree': ['Stonetree', 'Stone Tree'],
        'Rsutville': ['Rustville', 'Rsut Ville'],
        'Sunset Mesa': ['Sunset Mesa', 'Sunset Messa'],
        'Windfall': ['Windfall', 'Wind Fall'],
        'Chawlas Breach': ['Chawlas Breach', 'Chawlas Beach'],
        'Last Landings': ['Last Landings', 'Last Landing'],
        'Yangs Place': ['Yang Place', 'Yangs Place'],
        'Ostlers Claim': ['Ostlers Claim', 'Ostler Claim'],
        'Last Ditch': ['Last Ditch', 'Last Dtch'],
        'Cravers Ridge': ['Cravers Ridge', 'Craver Ridge'],
        'Bueno Ravine': ['Bueno Ravine', 'Buena Ravine'],
        'The Yard': ['The Yard', 'Yard'],
        'Shepherds Rest': ['Shepherds Rest', 'Shepherd Rest'],
        'Scrapers Turn': ['Scrapers Turn', 'Scraper Turn'],
        'Bullocks Reach': ['Bullocks Reach', 'Bullock Reach'],
        'Kinder Plots': ['Kinder Plots', 'Kinder Plot']
    },

    FullList: [
        '--Stations--',
        'Ruin Station',
        'Orbituary',
        'Patch City',
        'Starlight Service Station',
        'Checkmate',
        'Rods Fuel N Supplies',
        'Endgame',
        'Dudley & Daughters',
        'Rats Net',
        'Megumi Refueling',
        'Gaslight',
        '--Outposts--',
        'Stags Rut',
        'Arid Reach',
        'Jacksons Swap',
        'Narenas Rest',
        'The Golden Riviera',
        'Frigid Knot',
        'ShadowFall',
        'Fallow Field',
        'Goners Deal',
        'Sacrens Plot',
        'Rough Landing',
        'Blackrock Exchange',
        'Canard View',
        'Stonetree',
        '--Salvage Yards--',
        'Rsutville',
        'Sunset Mesa',
        'Windfall',
        'Chawlas Breach',
        'Last Landings',
        '--Farming Outposts--',
        'The Yard',
        'Shepherds Rest',
        'Scrapers Turn',
        'Bullocks Reach',
        'Kinder Plots',
        '--Mining Outposts--',
        'Yangs Place',
        'Ostlers Claim',
        'Last Ditch',
        'Cravers Ridge',
        'Bueno Ravine',
    ],

    commodities: [
        'Aluminum',
        'Carbon',
        'Corundum',
        'Processed Food',
        'Pressurized Ice',
        'Agricultural Supplies',
        'Quartz',
        'Silicon',
        'Stims',
        'Tin',
        'Titanium',
        'Tungsten',
        'Hydrogen',
        'Hydrogen Fuel',
        'Quantum Fuel',
        'Ship Ammunition',
        'Scrap',
        'Waste',
        'Ship Ammunition',
        'Quantum Fuel',
        'Corundum Raw',
        'Quartz Raw',
        'Silicon Raw',
        'Tin Raw',
        'Titanium Raw',
        'Tungsten Raw'
    ],
}